Add missing semicolon
Author: Andhieka Putra

Reasons for Change:
 - Got error when activating home manager

```
❯ home-manager switch --impure --flake "home-manager-config#$USER"
error: syntax error, unexpected '}', expecting ';'

       at /nix/store/py7qy51z4m66qd2jrpxwszmaayhwg8hg-source/home-template.nix:97:7:

           96|         mfa = "awsmfa auth -u <user> -t"
           97|       };
             |       ^
           98|
(use '--show-trace' to show detailed location information)
```

Changes:
 -